# -*- coding: utf-8 -*-

ENV_CONTENT_SERVER = 'CONTENT_SERVER'
ENV_CONTENT_KEY = 'CONTENT_KEY'

CFG_CONTENT_SERVER = 'server_url'
CFG_CONTENT_KEY = 'api_key'
CFG_WEATHER_TEMPLATE = 'weather_template'
CFG_SOCCER_TEMPLATE = 'soccer_template'
CFG_TIMEINFO_TEMPLATE = 'timeinfo_template'


CONTENT_SERVER_DEFAULT = 'https://content.emotibot.com'
CONTENT_KEY_DEFAULT = '2WDGS5SCH68RWDLC76BI9J6CZEKJM5QM'
